services:
    nginx:
        network_mode: host
        container_name: nginx
        volumes:
            - ~/docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ~/docker/cert:/etc/cert
        restart: always
        image: nginx:latest
    xray:
        container_name: xray
        network_mode: host
        volumes:
            - ~/docker/xray:/etc/xray
            - ~/docker/cert:/etc/cert
        restart: always
        image: teddysun/xray